#!/usr/bin/env python

import sys
import math

def factorize(n):
    """Return a factorization of n as a tuple (p, q)."""
    for i in range(2, int(math.sqrt(n))+1):
        if n % i == 0:
            return i, n // i
    return None

if __name__ == '__main__':
    if len(sys.argv) != 2:
        print(f"Usage: {sys.argv[0]} <file>")
        sys.exit(1)

    filename = sys.argv[1]

    with open(filename) as f:
        for line in f:
            n = int(line.strip())
            factors = factorize(n)
            if factors is not None:
                print(f"{n}={factors[0]}*{factors[1]}")
